# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: glauberrleite-dev
email: leite.glauber.rodrigues@gmail.com
description: An old-fashioned developer looking for new horizons, and keeping what is good (or at least nostalgic) from the past
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://glauberrleite.github.io" # the base hostname & protocol for your site
twitter_username: GlauberRLeite
github_username:  glauberrleite

include:
- _assets

layoutVars:
    default:
        relativepath: "./"
    post:
        relativepath: "../../../../"

# Build settings
markdown: kramdown
